### ISSUE TITLE
Igorrr Post

### ISSUE THREAD

**Issue by rreed** [makyo/salsa#1]
---
layout: post
title: Igorrr
author: Amdusias
---

A couple of days ago, [Igorrr](http://igorrr.com/) announced his fifth LP, _Savage Sinusoid_, on Metal Blade. I got really, really excited, because a new Igorrr album is an event for me. Usually, when...basically anyone I know reads the previous sentence, they get really confused. "What the fuck am I actually listening to?" gets said. Attempts to figure out the answer to that question are made. So yeah, here's the brief primer, I guess.

1) Igorrr has the single greatest producer vanity photo you will ever see. I mean, just look at it.

<img src="http://static.tvtropes.org/pmwiki/pub/images/98535977c314ef47eb29f5c9a8cec662.jpeg"/>

2) The rooster in that picture has a solo in his track Vegetable Soup.

<iframe src="https://embed.spotify.com/?uri=spotify%3Atrack%3A6q5iDgq3qEUEMeqffMzPu8" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>

3) His earlier music sits at the center of the Venn diagram of Venetian Snares, JS Bach, and your favorite death metal band.

<iframe src="https://embed.spotify.com/?uri=spotify%3Atrack%3A3gLUaPawGwUaFCTV79Uwsy" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>

4) If you've read all the way through "rooster solo plus Baroque death breakcore" and you're still here, you've probably already been convinced, so there isn't actually a number four.

-Ammy

**Comment by makyo** [comment]
mergéd
